version: '3'

services:
    jekyll:
        working_dir: /app/jekyll
        image: jekyll/jekyll:latest
        command: jekyll serve --watch --force_polling --verbose
        environment:
            VIRTUAL_HOST: slubi.se
            VIRTUAL_PORT: 4000
            LETSENCRYPT_HOST: slubi.se
            LETSENCRYPT_EMAIL: juliette.hayer@slu.se
        expose:
            - 4000
        volumes:
            - ./:/app/jekyll

networks:
    default:
        external:
            name: nginx-proxy
